### ISSUE TITLE
Returning empty column titles causes width error

### ISSUE THREAD

**Issue by samanehsan** [caneruguz/treebeard#60]
The `columnTitles` treebeard option is required, but returning an empty array (so as not to display the columns) causes the following error: 

![screen shot 2015-02-05 at 4 35 34 pm](https://cloud.githubusercontent.com/assets/6414394/6069762/111d9fb2-ad55-11e4-8c07-6f10cd0ecd93.png)

**Comment by caneruguz** [comment]
there is now an option to hide column titles within Treebeard that takes care of this. Thanks for reporting!
