### ISSUE TITLE
Allow disabling multiselect

### ISSUE THREAD

**Issue by samchrisinger** [caneruguz/treebeard#66]
![image](https://cloud.githubusercontent.com/assets/2207561/6398900/f08f5b00-bdbc-11e4-9318-bd1c0c5feb79.png)

Sometimes rows get unexpectedly highlighted red. This is related to the .tb-multiselect class. There needs to be a way to disable this.

**Comment by caneruguz** [comment]
There is an option for turning off multiselect: 
```options.multiselect = false; ```

or the highlight color can be changed with this option:
```options.hoverClassMultiselect = 'my-class';```

Does that resolve these issue or is there something else going on?
