### ISSUE TITLE
`#tb-body` selector is hardcoded in multiple places

### ISSUE THREAD

**Issue by sloria** [caneruguz/treebeard#76]
This makes the API brittle and may also lead to problems with multiple Treebeards on a page.

**Comment by caneruguz** [comment]
This is already addressed in josh's updates so if there are any lingering
global selectors I need to fix them. Can you point out to specific ones?

**Comment by sloria** [comment]
Josh only changed some of the selectors. `#tb-body` is still in the code: https://github.com/caneruguz/treebeard/blob/d6e486b5dcfb3efd062758c1ec7c92735203e5d7/scripts/grid.js#L220

**Comment by caneruguz** [comment]
That's actually not wrong. The code is not a jquery selector, it's running a function called select:
```
ctrl.select('#tb-tbody')
```

That function is specifying which grid should be selected like here:
```js
        /**
         * Prepend selector with ID of root DOM node
         * @param {String} selector CSS selector
         */
        this.select = function(selector) {
            return $('#' + self.options.divID + ' ' + selector);
        };
```

There shouldn't be any stand alone selectors like this:
```js
// wrong:
    $('#tb-tbody').something();
```

**Comment by sloria** [comment]
But there are still multiple multiple elements on the page with the same CSS ID. I came across this in reviewing https://github.com/CenterForOpenScience/osf.io/pull/2229/files , which has this code 

```js
$('#tb-tbody').scrollTop(scrollTo);
```

If there were multiple treebeards, it wouldn't be clear which one this was selecting.

**Comment by caneruguz** [comment]
Yes correct, my comment above still stands, these stand alone instances should not be there. Your prior comment had an example of legitimate use. So this issue is valid and needs attention to comb through code for stand alone selectors.

**Comment by caneruguz** [comment]
That's not a treebeard issue though, the PR there is doing the wrong implementation, Can you add it as a line note for the PR? 

Can we make it clear whether any Treebeard code has this?  Otherwise I'll need to close the issue.

**Comment by caneruguz** [comment]
Since there isn't a specific pointer to Treebeard code doing this I'm closing the issue. Reopen if one found.
