### ISSUE TITLE
Allow modal to be dismissed by clicking in grayed-out area

### ISSUE THREAD

**Issue by samchrisinger** [caneruguz/treebeard#77]
Bootbox, for example, has an option to dismiss modals by pressing <ESC> and also an option to dismiss the modal when a user clicks in the grayed-out background. 

This would be a nice feature.

**Comment by caneruguz** [comment]
Fixed in this commit: 
https://github.com/caneruguz/treebeard/commit/7e3162ec3a003575173045f8f5510fd718e5a111

Closes when clicked on the shaded area but not on the modal itself.
