### ISSUE TITLE
Modal close button cursor style should be pointer

### ISSUE THREAD

**Issue by samchrisinger** [caneruguz/treebeard#78]
![screen shot 2015-05-05 at 9 37 27 am](https://cloud.githubusercontent.com/assets/2207561/7473623/8f3795ce-f30a-11e4-889e-9de29dfa41e6.png)

Mousing over the close button on the TB modal does not change the cursor style. It should probably be cursor: pointer, or customizable by the user.

**Comment by caneruguz** [comment]
This icon is customizable by user through the css: 
```css
.tb-modal-dismiss {
  cursor: pointer;
}
```

But default css should have this too.

**Comment by samchrisinger** [comment]
Do you plan to fix this or do I need to override?

**Comment by caneruguz** [comment]
I'll take care of both osf and treebeard repos.

**Comment by caneruguz** [comment]
Resolved in this commit for Treebeard:
https://github.com/caneruguz/treebeard/commit/0c675b5694b0e3801883d45c0bcf088ff691086d
