### ISSUE TITLE
Treebeard modal setting should follow the osf style guide

### ISSUE THREAD

**Issue by haoyuchen1992** [caneruguz/treebeard#87]
Issue related to Trello bug: 
https://trello.com/c/C8kEBqVK/135-inconsistent-style-of-top-right-x-icon-in-modals

Current Treebeard modal could only be customized on modal content and foot button.  -- https://github.com/caneruguz/treebeard/blob/develop/dist/treebeard.js#L290

So it should be follow the modal on the osf style guide and allow user to  set modal title, modal content, and modal button respectively.

**Comment by caneruguz** [comment]
This commit should resolve this issue: 
https://github.com/caneruguz/treebeard/commit/01707a0824f48c48d536d238ad3a0f92cc936f5c
